***TensorFlow***

In [1]:
#import a Tensorflow
import tensorflow as tf
print(tf.__version__)  

2.12.0


In [2]:
#Creating Tensors with tf.constant()
#Creat a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#Check the number of dimentions of tensor
scalar.ndim

0

In [4]:
#Create a vector (more than 0 dimentions)
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
#Create a Matrix (more than one dimentions)
matrix = tf.constant([[10,8],
                      [5,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 5, 10]])>

In [7]:
matrix.ndim

2

In [8]:
#Create another matrix and define the DataType

New_matrix = tf.constant([[10,2],
                          [5,3],
                          [8,4]],dtype=tf.float16)
New_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  2.],
       [ 5.,  3.],
       [ 8.,  4.]], dtype=float16)>

In [9]:
New_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
tensor.ndim

3

**Creating Tensors with tf.Variable()**

In [12]:
# Create the same tensor with tf.varibale and tf.constant
Changeable_Tensor = tf.Variable([10,8])
UnChangeable_Tensor = tf.constant([10,8])

Changeable_Tensor , UnChangeable_Tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8])>)

In [13]:
#Won't Error
Changeable_Tensor[0].assign(7)
Changeable_Tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 8])>

In [14]:
#Will get error
UnChangeable_Tensor[0],assign(8)

NameError: name 'assign' is not defined

**Create Random Tensor**

In [15]:
#Create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(32)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(32)
random_2 = random_2.normal(shape=(3,2))

# Are they equal ?
random_1, random_2 ,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [16]:
#Create two random (and different) tensors

random_3 = tf.random.Generator.from_seed(33)
random_3 = random_3.normal(shape=(3,2))
random_4 = tf.random.Generator.from_seed(32)
random_4 = random_4.normal(shape=(3,2))

# Are they equal ?
random_3, random_4 ,random_3==random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.1589871 ,  1.302304  ],
        [ 0.9592239 ,  0.85874265],
        [-1.5181769 ,  1.4020647 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [17]:
#Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10,2],
                            [4,6],
                            [7,8]])

not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  2],
       [ 4,  6],
       [ 7,  8]])>

In [57]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [10,  2],
       [ 4,  6]])>

In [19]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 4,  6],
       [10,  2]])>

In [41]:
#Shuffle in the same order every time

#Set the Global random seed
tf.random.set_seed(42)

#set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  2],
       [ 4,  6],
       [ 7,  8]])>

In [62]:
#Set the Global random seed
tf.random.set_seed(42)

#set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 7,  8],
       [10,  2]])>

**Other Ways to make Tensor**

In [63]:
#Make a tensor of all ones
tf.ones(shape=(4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [64]:
#Make a tensor of all Zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [73]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)

A = tf.constant(numpy_A, shape=[2,3,4])
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>)

**Getting Information from Tensors(shape,rank,size)**

In [75]:
# Create a rank 4 tensor (4-dimentions)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [76]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [77]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [78]:
rank_4_tensor 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Adding dimention
rank_5_tensor = rank_4_tensor[..., tf.newaxis]
rank_5_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

**Basic Operations (+,-,*,/)**

In [82]:
tensor = tf.constant([[10,8],
                     [7,8]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 7,  8]])>

In [83]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 18],
       [17, 18]])>

In [84]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -2],
       [-3, -2]])>

In [85]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 40],
       [35, 40]])>

In [86]:
tensor / 3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 2.66666667],
       [2.33333333, 2.66666667]])>

In [87]:
#Usi the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 40],
       [35, 40]])>

**Matrix Multiplication**

In [88]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 7,  8]])>

In [89]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[156, 144],
       [126, 120]])>

In [90]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[156, 144],
       [126, 120]])>

In [91]:
tensor.shape

TensorShape([2, 2])

In [93]:
x = tf.constant([[4,8,3],
                [4,2,7]])
x.shape

TensorShape([2, 3])

In [ ]:
#Re-shape the Matrix
tf.reshape(x, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 8],
       [3, 4],
       [2, 7]])>

In [95]:
tensor @ x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[72, 96, 86],
       [60, 72, 77]])>

In [97]:
y = tensor @ x
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[72, 96, 86],
       [60, 72, 77]])>

In [ ]:
#Transpose (2,3) convert to (3,2)
tf.transpose(y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[72, 60],
       [96, 72],
       [86, 77]])>

**Changing dataType of a Tensor (Cast)**  

In [99]:
#Create a new Tensor

A = tf.constant([1.5,1.3])

B = tf.constant([4,5])

B.dtype ,A.dtype 

(tf.int32, tf.float32)

In [102]:
A = tf.cast(A, dtype=tf.float16)
A.dtype

tf.float16

In [109]:
B= tf.cast(A,dtype=tf.int8)
B.dtype

tf.int8

**Getting The Absolute Value (tf.abs)**

In [110]:
C = tf.constant([-5,-9])

In [112]:
tf.abs(C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 9])>

In [113]:
D = tf.constant([-7,5])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7,  5])>

In [114]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5])>

**Finding the min,max,mean,sum (aggregation)**

In [116]:
E = tf.constant(np.random.randint(low=0,high=80, size=40))
E

<tf.Tensor: shape=(40,), dtype=int32, numpy=
array([ 2, 35, 70, 39, 33, 22, 68, 50, 13, 26, 67, 39, 41, 20, 13, 75,  6,
        4, 53, 58, 71, 57, 31, 45, 44, 63, 74, 17, 25, 21, 15, 76, 41, 76,
       57, 11, 48, 36,  2, 67])>

In [118]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [119]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=76>

In [120]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [121]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1611>

**Finding the Position Maximum and Minimum**

In [128]:
F = tf.constant(np.random.random(20))
F

<tf.Tensor: shape=(20,), dtype=float64, numpy=
array([0.25506828, 0.4864494 , 0.66715014, 0.37729616, 0.62863581,
       0.68008692, 0.84798364, 0.91405283, 0.08360429, 0.89970238,
       0.49111806, 0.37504473, 0.435451  , 0.65286089, 0.10855164,
       0.13766379, 0.61805011, 0.15166925, 0.14111982, 0.00180472])>

In [129]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [130]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [134]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.001804718466335009>

In [132]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9140528274036522>

**One-Hot Encoding**

In [137]:
OHE_List = [0,1,2,3]

tf.one_hot(OHE_List, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [141]:
# On_values=1 and Off_values=0
tf.one_hot(OHE_List, depth=4, on_value= "Hi...",off_value="***")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hi...', b'***', b'***', b'***'],
       [b'***', b'Hi...', b'***', b'***'],
       [b'***', b'***', b'Hi...', b'***'],
       [b'***', b'***', b'***', b'Hi...']], dtype=object)>

**Finding access to GPU**

In [144]:
print(tf.config.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [146]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


In [149]:
import tensorflow as tf
print("TensorFlow:", tf.__version__)
print("GPUs:", tf.config.list_physical_devices('GPU'))


TensorFlow: 2.12.0
GPUs: []
